name: Build and push multi-platform Docker images

on:
  push:
    branches: '*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux/amd64, linux/arm64]
        tag: [amd64, arm64]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Obtain repository and tag names
        shell: bash
        run: |
              if [ -z "${{ secrets.DOCKER_HUB_REPO }}" ]; then
                  echo "uname=${{ secrets.DOCKER_HUB_USERNAME }}" >> $GITHUB_OUTPUT
              else
                  echo "uname=${{ secrets.DOCKER_HUB_REPO }}" >> $GITHUB_OUTPUT
              fi
              echo "repo=$(echo ${GITHUB_REPOSITORY} | awk -F / '{print $2}')"  >> $GITHUB_OUTPUT
              echo "tag=$(echo ${GITHUB_REF#refs/heads/} | sed 's/^main$/latest/g')" >> $GITHUB_OUTPUT
        id: extract_tag
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          platforms: ${{ matrix.platform }}
          push: true
          tags: ${{ steps.extract_tag.outputs.uname }}/${{ steps.extract_tag.outputs.repo }}:${{ steps.extract_tag.outputs.tag }}-${{ matrix.tag }}

  push-manifest:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Obtain repository and tag names
        shell: bash
        run: |
              if [ -z "${{ secrets.DOCKER_HUB_REPO }}" ]; then
                  echo "uname=${{ secrets.DOCKER_HUB_USERNAME }}" >> $GITHUB_OUTPUT
              else
                  echo "uname=${{ secrets.DOCKER_HUB_REPO }}" >> $GITHUB_OUTPUT
              fi
              echo "repo=$(echo ${GITHUB_REPOSITORY} | awk -F / '{print $2}')"  >> $GITHUB_OUTPUT
              echo "tag=$(echo ${GITHUB_REF#refs/heads/} | sed 's/^main$/latest/g')" >> $GITHUB_OUTPUT
        id: extract_tag
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Pull Docker images
        run: |
          docker pull ${{ steps.extract_tag.outputs.uname }}/${{ steps.extract_tag.outputs.repo }}:${{ steps.extract_tag.outputs.tag }}-amd64
          docker pull ${{ steps.extract_tag.outputs.uname }}/${{ steps.extract_tag.outputs.repo }}:${{ steps.extract_tag.outputs.tag }}-arm64

      - name: Create and push Docker manifest
        run: |
          docker manifest create ${{ steps.extract_tag.outputs.uname }}/${{ steps.extract_tag.outputs.repo }}:${{ steps.extract_tag.outputs.tag }} \
            --amend ${{ steps.extract_tag.outputs.uname }}/${{ steps.extract_tag.outputs.repo }}:${{ steps.extract_tag.outputs.tag }}-amd64 \
            --amend ${{ steps.extract_tag.outputs.uname }}/${{ steps.extract_tag.outputs.repo }}:${{ steps.extract_tag.outputs.tag }}-arm64
          docker manifest push ${{ steps.extract_tag.outputs.uname }}/${{ steps.extract_tag.outputs.repo }}:${{ steps.extract_tag.outputs.tag }}
