name: Docker Image CI

on:
  push:
    branches: '*'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Obtain tag name from branch name
        shell: bash
        run: |
             echo "##[set-output name=tag;]$(echo ${GITHUB_REF#refs/heads/} | sed 's/^main$/latest/g')"
             echo "##[set-output name=repo;]$(echo ${GITHUB_REPOSITORY} | awk -F / '{print $2}')"
        id: extract_tag
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ steps.extract_tag.outputs.repo }}:${{ steps.extract_tag.outputs.tag }}
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/${{ steps.extract_tag.outputs.tag }}:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/${{ steps.extract_tag.outputs.tag }}:buildcache,mode=max

# Reference: https://docs.docker.com/ci-cd/github-actions/
